#ifndef OpenAphid_AJOABindingTypes_h
#define OpenAphid_AJOABindingTypes_h

enum AJOABindingType {
	AJActionBindingType = 0,
	AJAffineTransformationBindingType,
	AJAnimationBindingType,
	AJCameraBindingType,
	AJColorBindingType,
	AJColorNodeBindingType,
	AJConsoleBindingType,
	AJDirectorBindingType,
	AJDynamicBindingBindingType,
	AJEaseActionBindingType,
	AJEventBindingType,
	AJFiniteTimeActionBindingType,
	AJFontBindingType,
	AJGradientNodeBindingType,
	AJGridBaseActionBindingType,
	AJInstantActionBindingType,
	AJIntervalActionBindingType,
	AJLabelTTFBindingType,
	AJNamespaceActionsBindingType,
	AJNamespaceAndroidBindingType,
	AJNamespaceAphidBindingType,
	AJNamespaceCoreBindingType,
	AJNamespaceExtBindingType,
	AJNamespaceG2DBindingType,
	AJNamespaceJSBindingType,
	AJNodeBindingType,
	AJNodeListBindingType,
	AJOAGlobalObjectBindingType,
	AJParticleSystemBindingType,
	AJPointBindingType,
	AJProgressEventBindingType,
	AJRectBindingType,
	AJSceneBindingType,
	AJSizeBindingType,
	AJSpriteBindingType,
	AJSpriteBatchNodeBindingType,
	AJSpriteFrameBindingType,
	AJTexture2DBindingType,
	AJTouchBindingType,
	AJTouchEventBindingType,
	AJTouchListBindingType,
	AJVector2BindingType,
	AJVector3BindingType,
	AJXMLHttpRequestBindingType,
	AJOABindingTypeMax = 44
};

#endif