/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openaphid_internal_AppDelegate */

#ifndef _Included_org_openaphid_internal_AppDelegate
#define _Included_org_openaphid_internal_AppDelegate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openaphid_internal_AppDelegate
 * Method:    nativeInitialize
 * Signature: (ZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openaphid_internal_AppDelegate_nativeInitialize
  (JNIEnv *, jclass, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
